# Build settings
markdown: redcarpet
highlighter: pygments
permalink: none

# Site settings
title: "Vluxe"
description:  A collection of interesting computer science and programming topics. Updated weekly.

#blog logo
logo: "/assets/images/logo.png"
# blog cover
cover: "/assets/images/plans.png"

url: http://vluxe.io

social:
  - icon: twitter
    url:  https://twitter.com/vluxeio
    desc: Follow me on twitter
    share_url: http://twitter.com/share
    share_title: ?text=
    share_link: "&amp;url="

  - icon: github
    url:  https://github.com/vluxe
    desc: Fork me on github
    share_url:
    share_title:
    share_link:

authors:
  - name: Dalton Cherry
    url:  http://daltoniam.com
    image: http://www.gravatar.com/avatar/2fdc7b889f35118a7334187b15c5b957.png?r=x&amp;s=320
    bio: Dalton Cherry. Developer. Disciple. Computer science aficionado. Mobile enthusiast. Drum machine. Paintball extraordinaire. The next American Ninja Warrior.

  - name: Austin Cherry
    url:  http://austincherry.me
    image: http://www.gravatar.com/avatar/4278893e11f873d60fede435f1ae08aa.png?r=x&amp;s=320
    bio: Master tactician. Defeated an entrie armada of klingon war birds. The true last samurai. Believer in Jesus. Music fanatic and guitar player extraordinaire.