# Build settings
markdown: redcarpet
highlighter: pygments
permalink: /:title.html
paginate: 5

# gems and other configs
gems: [jekyll-paginate]

# Site settings
title: "Vluxe"
name: 'Vluxe'
description: Simply Superb Software

#blog logo
logo: "/assets/images/logo.png"
# blog cover
cover: "/assets/images/plans.jpg"

url: http://vluxe.io
baseurl: /

google_analytics: UA-52182448-1

social:
  - icon: twitter
    url:  https://twitter.com/vluxeio
    desc: Follow me on twitter
    share_url: http://twitter.com/share
    share_title: ?text=
    share_link: "&amp;url="

  - icon: github
    url:  https://github.com/vluxe
    desc: Fork me on github
    share_url:
    share_title:
    share_link:

  - icon: envelope
    url:  mailto:dalton@vluxe.io
    desc: Contact Us
    share_url:
    share_title:
    share_link:

authors:
  - name: Dalton Cherry
    slug: dalton
    url:  http://daltoniam.com
    image: http://www.gravatar.com/avatar/2fdc7b889f35118a7334187b15c5b957.png?r=x&amp;s=320
    twitter: daltoniam
    location: Austin, Texas
    bio: Dalton Cherry. Developer. Disciple. Computer science aficionado. Mobile enthusiast. Drum machine. Paintball extraordinaire. The next American Ninja Warrior.

  - name: Austin Cherry
    slug: austin
    url:  http://austincherry.me
    twitter: acmacalister
    location: Austin, Texas
    image: https://s.gravatar.com/avatar/b318dde74289b9eb1cfdb0ecff012742?s=320
    bio: Master tactician. Defeated an entrie armada of klingon war birds. The true last samurai. Believer in Jesus. Music fanatic and guitar player extraordinaire.